import type { Locale } from "@/i18n";

export const studioSupplementalCopy = {
  en: {
    articlesDescription: "Review every story, language and publishing state.",
    dashboardKicker: "Editorial command centre",
    totalStories: "Total stories",
    publishedStories: "Published",
    scheduledStories: "Scheduled",
    draftStories: "In progress",
    recentStories: "Recently updated",
    featuredLabel: "Featured story",
    localeLabel: "Language",
    coverAltLabel: "Cover image description",
    distributionHelp: "Prepare this story for the channels managed by the editorial queue.",
    scheduledRequired: "Choose a publishing date for scheduled stories.",
    validationError: "Check the highlighted fields and try again.",
    saveError: "The story could not be saved. Try again.",
    notFound: "This story is no longer available.",
    contentHelp: "Use ## for section headings. Separate paragraphs with a blank line.",
    mediaTitle: "Media library",
    mediaDescription: "Every cover asset currently referenced by this language's stories.",
    assetUrl: "Asset URL",
    usedBy: "Used by",
    noAssets: "No media assets are referenced yet.",
    distributionTitle: "Distribution queue",
    distributionDescription: "Real channel selections saved with NEURA stories.",
    readyItems: "prepared items",
    noDistribution: "No story is prepared for distribution yet.",
    newsletterTitle: "Newsletter intake",
    newsletterDescription: "The public briefing form accepts and deduplicates subscriptions.",
    newsletterCapability: "Subscription capture is active",
    newsletterBoundary: "Subscriber analytics are not exposed by the current write-only newsletter port, so no unverified totals are shown here.",
    openBriefing: "Open the public briefing",
    viewStory: "View story",
    editStory: "Edit story",
    deletePending: "Deleting…",
  },
  it: {
    articlesDescription: "Controlla ogni storia, lingua e stato di pubblicazione.",
    dashboardKicker: "Centro di comando editoriale",
    totalStories: "Storie totali",
    publishedStories: "Pubblicate",
    scheduledStories: "Programmate",
    draftStories: "In lavorazione",
    recentStories: "Aggiornate di recente",
    featuredLabel: "Storia in primo piano",
    localeLabel: "Lingua",
    coverAltLabel: "Descrizione immagine di copertina",
    distributionHelp: "Prepara questa storia per i canali gestiti dalla coda editoriale.",
    scheduledRequired: "Scegli una data di pubblicazione per le storie programmate.",
    validationError: "Controlla i campi evidenziati e riprova.",
    saveError: "Non è stato possibile salvare la storia. Riprova.",
    notFound: "Questa storia non è più disponibile.",
    contentHelp: "Usa ## per i titoli di sezione. Separa i paragrafi con una riga vuota.",
    mediaTitle: "Libreria media",
    mediaDescription: "Tutti gli asset di copertina usati dalle storie in questa lingua.",
    assetUrl: "URL asset",
    usedBy: "Usato da",
    noAssets: "Nessun asset media è ancora referenziato.",
    distributionTitle: "Coda di distribuzione",
    distributionDescription: "Selezioni di canale reali salvate con le storie NEURA.",
    readyItems: "elementi preparati",
    noDistribution: "Nessuna storia è ancora pronta per la distribuzione.",
    newsletterTitle: "Raccolta newsletter",
    newsletterDescription: "Il modulo pubblico del briefing accetta e deduplica le iscrizioni.",
    newsletterCapability: "La raccolta iscrizioni è attiva",
    newsletterBoundary: "Le statistiche degli iscritti non sono esposte dal port newsletter, che è solo in scrittura: qui non mostriamo totali non verificati.",
    openBriefing: "Apri il briefing pubblico",
    viewStory: "Vedi storia",
    editStory: "Modifica storia",
    deletePending: "Eliminazione…",
  },
} as const satisfies Record<Locale, Record<string, string>>;
