import type { Locale } from "@/i18n";
import type { MarkdownEditorCopy } from "./markdown-editor";

export const studioSupplementalCopy = {
  en: {
    articlesDescription: "Review every story, language and publishing state.",
    dashboardKicker: "Editorial command centre",
    totalStories: "Total stories",
    publishedStories: "Published",
    scheduledStories: "Scheduled",
    draftStories: "In progress",
    recentStories: "Recently updated",
    featuredLabel: "Featured story",
    localeLabel: "Language",
    coverAltLabel: "Cover image description",
    distributionHelp: "Prepare this story for the channels managed by the editorial queue.",
    scheduledRequired: "Choose a publishing date for scheduled stories.",
    validationError: "Check the highlighted fields and try again.",
    saveError: "The story could not be saved. Try again.",
    notFound: "This story is no longer available.",
    contentHelp: "Write in Markdown. Use the toolbar or keyboard shortcuts, then check the live preview.",
    markdown: {
      toolbar: "Markdown formatting",
      viewMode: "Editor view",
      write: "Write",
      preview: "Preview",
      split: "Split",
      heading: "Section heading",
      bold: "Bold",
      italic: "Italic",
      strike: "Strikethrough",
      link: "Link",
      quote: "Quote",
      bullets: "Bulleted list",
      numbered: "Numbered list",
      checklist: "Task list",
      code: "Code",
      image: "Image",
      words: "words",
      characters: "characters",
      emptyPreview: "Start writing to see the rendered story.",
      imageUnavailable: "Image unavailable",
    },
    mediaTitle: "Media library",
    mediaDescription: "Every cover asset currently referenced by this language's stories.",
    assetUrl: "Asset URL",
    usedBy: "Used by",
    noAssets: "No media assets are referenced yet.",
    distributionTitle: "Distribution queue",
    distributionDescription: "Real channel selections saved with NEURA stories.",
    readyItems: "prepared items",
    noDistribution: "No story is prepared for distribution yet.",
    distributionUpdated: "Distribution item updated.",
    distributionError: "The distribution item could not be updated.",
    distributionMessage: "Channel copy",
    distributionUrl: "Published URL",
    distributionSchedule: "Schedule",
    distributionStatus: "Workflow status",
    saveDistribution: "Save item",
    openPublication: "Open publication",
    newsletterTitle: "Newsletter intake",
    newsletterDescription: "Manage the consented audience captured by the public briefing form.",
    newsletterCapability: "Subscription capture is active",
    newsletterBoundary: "NEURA stores consent and audience state directly. Export is available for an authorized mailing provider; no delivery is claimed by this platform.",
    openBriefing: "Open the public briefing",
    exportAudience: "Export CSV",
    subscriberSearch: "Search email",
    allSubscribers: "All statuses",
    activeSubscribers: "Active",
    unsubscribedSubscribers: "Unsubscribed",
    noSubscribers: "No subscriptions match this view.",
    subscriberUpdated: "Subscriber status updated.",
    sourceLabel: "Source",
    consentedLabel: "Consented",
    unsubscribe: "Unsubscribe",
    reactivate: "Reactivate",
    audiencePagination: "Audience pages",
    showingSubscribers: "Showing",
    previousPage: "Previous",
    nextPage: "Next",
    mediaUploadTitle: "Upload a cover asset",
    mediaUploadHelp: "AVIF, GIF, JPEG, PNG or WebP. Maximum 8 MB. Files are served from Supabase Storage.",
    mediaUploadAction: "Upload image",
    mediaReadOnly: "Demo mode includes bundled media but cannot persist uploads. Connect Supabase to enable the library.",
    mediaUploaded: "Media asset uploaded.",
    mediaDeleted: "Media asset deleted.",
    mediaError: "The media operation could not be completed.",
    mediaInUse: "This asset is still used by an article and cannot be deleted.",
    deleteAsset: "Delete asset",
    unusedAsset: "Not used by any article",
    viewStory: "View story",
    editStory: "Edit story",
    deletePending: "Deleting…",
  },
  it: {
    articlesDescription: "Controlla ogni storia, lingua e stato di pubblicazione.",
    dashboardKicker: "Centro di comando editoriale",
    totalStories: "Storie totali",
    publishedStories: "Pubblicate",
    scheduledStories: "Programmate",
    draftStories: "In lavorazione",
    recentStories: "Aggiornate di recente",
    featuredLabel: "Storia in primo piano",
    localeLabel: "Lingua",
    coverAltLabel: "Descrizione immagine di copertina",
    distributionHelp: "Prepara questa storia per i canali gestiti dalla coda editoriale.",
    scheduledRequired: "Scegli una data di pubblicazione per le storie programmate.",
    validationError: "Controlla i campi evidenziati e riprova.",
    saveError: "Non è stato possibile salvare la storia. Riprova.",
    notFound: "Questa storia non è più disponibile.",
    contentHelp: "Scrivi in Markdown. Usa la toolbar o le scorciatoie, poi controlla l’anteprima dal vivo.",
    markdown: {
      toolbar: "Formattazione Markdown",
      viewMode: "Vista editor",
      write: "Scrivi",
      preview: "Anteprima",
      split: "Affianca",
      heading: "Titolo di sezione",
      bold: "Grassetto",
      italic: "Corsivo",
      strike: "Barrato",
      link: "Link",
      quote: "Citazione",
      bullets: "Elenco puntato",
      numbered: "Elenco numerato",
      checklist: "Lista attività",
      code: "Codice",
      image: "Immagine",
      words: "parole",
      characters: "caratteri",
      emptyPreview: "Inizia a scrivere per vedere la storia renderizzata.",
      imageUnavailable: "Immagine non disponibile",
    },
    mediaTitle: "Libreria media",
    mediaDescription: "Tutti gli asset di copertina usati dalle storie in questa lingua.",
    assetUrl: "URL asset",
    usedBy: "Usato da",
    noAssets: "Nessun asset media è ancora referenziato.",
    distributionTitle: "Coda di distribuzione",
    distributionDescription: "Selezioni di canale reali salvate con le storie NEURA.",
    readyItems: "elementi preparati",
    noDistribution: "Nessuna storia è ancora pronta per la distribuzione.",
    distributionUpdated: "Elemento di distribuzione aggiornato.",
    distributionError: "Non è stato possibile aggiornare l'elemento di distribuzione.",
    distributionMessage: "Testo per il canale",
    distributionUrl: "URL pubblicato",
    distributionSchedule: "Programmazione",
    distributionStatus: "Stato del flusso",
    saveDistribution: "Salva elemento",
    openPublication: "Apri pubblicazione",
    newsletterTitle: "Raccolta newsletter",
    newsletterDescription: "Gestisci il pubblico consenziente raccolto dal modulo briefing.",
    newsletterCapability: "La raccolta iscrizioni è attiva",
    newsletterBoundary: "NEURA conserva direttamente consenso e stato del pubblico. L'export può essere usato con un provider autorizzato; la piattaforma non dichiara invii esterni.",
    openBriefing: "Apri il briefing pubblico",
    exportAudience: "Esporta CSV",
    subscriberSearch: "Cerca email",
    allSubscribers: "Tutti gli stati",
    activeSubscribers: "Attivi",
    unsubscribedSubscribers: "Disiscritti",
    noSubscribers: "Nessuna iscrizione corrisponde a questa vista.",
    subscriberUpdated: "Stato dell'iscritto aggiornato.",
    sourceLabel: "Origine",
    consentedLabel: "Consenso",
    unsubscribe: "Disiscrivi",
    reactivate: "Riattiva",
    audiencePagination: "Pagine del pubblico",
    showingSubscribers: "Risultati",
    previousPage: "Precedente",
    nextPage: "Successiva",
    mediaUploadTitle: "Carica un asset di copertina",
    mediaUploadHelp: "AVIF, GIF, JPEG, PNG o WebP. Massimo 8 MB. I file sono serviti da Supabase Storage.",
    mediaUploadAction: "Carica immagine",
    mediaReadOnly: "La modalità demo include i media integrati ma non salva upload. Collega Supabase per abilitare la libreria.",
    mediaUploaded: "Asset media caricato.",
    mediaDeleted: "Asset media eliminato.",
    mediaError: "Non è stato possibile completare l'operazione media.",
    mediaInUse: "Questo asset è ancora usato da un articolo e non può essere eliminato.",
    deleteAsset: "Elimina asset",
    unusedAsset: "Non usato da alcun articolo",
    viewStory: "Vedi storia",
    editStory: "Modifica storia",
    deletePending: "Eliminazione…",
  },
} as const satisfies Record<Locale, Record<string, string | MarkdownEditorCopy>>;
